**Tools - NumPy**

*NumPy is the fundamental library for scientific computing with Python. NumPy is centered around a powerful N-dimensional array object, and it also contains useful linear algebra, Fourier transform, and random number functions.*

# Creating arrays
Let's import `numpy`. Most people import it as `np`:

In [0]:
import numpy as np

## `np.zeros`

The `zeros` function creates an array containing any number of zeros:

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

It's just as easy to create a 2D array (ie. a matrix) by providing a tuple with the desired number of rows and columns. For example, here's a 3x4 matrix:

In [18]:
a = np.zeros((3,4))
print(a)

# NumPy arrays have the type `ndarray`
print(type(a))

b = [[0]*4]*3
print(b)

print(type(b))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<type 'numpy.ndarray'>
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
<type 'list'>


## Some vocabulary

* In NumPy, each dimension is called an **axis**.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the above matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)

In [19]:
a.shape

(3, 4)

In [20]:
a.ndim  # rank: equal to len(a.shape)

2

In [21]:
a.size

12

## N-dimensional arrays
You can also create an N-dimensional array of arbitrary rank. For example, here's a 3D array (rank=3), with shape `(2,3,4)`:

In [22]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## `np.ones`
Many other NumPy functions create `ndarrays`.

Here's a 3x4 matrix full of ones:

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## `np.full`
Creates an array of the given shape initialized with the given value. Here's a 3x4 matrix full of `π`.

In [24]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

## `np.empty`
An uninitialized 2x3 array (its content is not predictable, as it is whatever is in memory at that point):

In [25]:
np.empty((2,3))

array([[4.64484217e-310, 4.64484115e-310, 4.64484068e-310],
       [6.90788679e-310, 0.00000000e+000, 0.00000000e+000]])

## np.array
Of course you can initialize an `ndarray` using a regular python list. Just call the `array` function:

In [26]:
np.array([[1,2,3,4], [10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

## `np.arange`
You can create an `ndarray` using NumPy's `range` function, which is similar to python's built-in `range` function:

In [27]:
np.arange(1, 5)

array([1, 2, 3, 4])

It also works with floats:

In [28]:
np.arange(1.0, 5.0)

array([1., 2., 3., 4.])

Of course you can provide a step parameter:

In [29]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## `np.linspace`
For this reason, it is generally preferable to use the `linspace` function instead of `arange` when working with floats. The `linspace` function returns an array containing a specific number of points evenly distributed between two values (note that the maximum value is *included*, contrary to `arange`):

In [30]:
print(np.linspace(0, 5/3, 6))

[0.  0.2 0.4 0.6 0.8 1. ]


## `np.rand` and `np.randn`
A number of functions are available in NumPy's `random` module to create `ndarray`s initialized with random values.
For example, here is a 3x4 matrix initialized with random floats between 0 and 1 (uniform distribution):

In [31]:
np.random.rand(3,4)

array([[0.99527464, 0.38890842, 0.08968796, 0.71176508],
       [0.8602957 , 0.18817913, 0.59364832, 0.3880812 ],
       [0.31445283, 0.41692357, 0.33375932, 0.43989931]])

__Exercise__: Generate 1000 random floats between $m$ and $n$ using `np.random.rand()`

In [0]:
m + np.random.rand(1000)*(n-m)

Here's a 3x4 matrix containing random floats sampled from a univariate [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) (Gaussian distribution) of mean 0 and variance 1:

In [32]:
np.random.randn(3,4)

array([[ 0.07073808,  0.72072018,  0.20084542,  0.46560129],
       [ 0.91486745,  1.5363939 ,  0.84776448, -0.28508015],
       [-1.85461368,  2.57789506, -0.05534318,  0.61001444]])

# Array data

## `dtype`
NumPy's `ndarray`s are also efficient in part because all their elements must have the same type (usually numbers).
You can check what the data type is by looking at the `dtype` attribute:

In [33]:
c = np.arange(1, 5)
print(c.dtype, c)

(dtype('int64'), array([1, 2, 3, 4]))


In [34]:
c = np.arange(1.0, 5.0)
print(c.dtype, c)

(dtype('float64'), array([1., 2., 3., 4.]))


Instead of letting NumPy guess what data type to use, you can set it explicitly when creating an array by setting the `dtype` parameter:

In [35]:
d = np.arange(1, 5, dtype=np.complex64)
print(d.dtype, d)

(dtype('complex64'), array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex64))


Available data types include `int8`, `int16`, `int32`, `int64`, `uint8`|`16`|`32`|`64`, `float16`|`32`|`64` and `complex64`|`128`. Check out [the documentation](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html) for the full list.

## `itemsize`
The `itemsize` attribute returns the size (in bytes) of each item:

In [36]:
e = np.arange(1, 5, dtype=np.complex64)
e.itemsize

8

# Reshaping an array
## In place
Changing the shape of an `ndarray` is as simple as setting its `shape` attribute. However, the array's size must remain the same.

In [37]:
g = np.arange(24)
print(g)
print("No. dimensions:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
('No. dimensions:', 1)


In [38]:
g.shape = (6, 4)
print(g)
print("No. dimensions:", g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
('No. dimensions:', 2)


In [39]:
g.shape = (2, 3, 4)
print(g)
print("No. dimensions:", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
('No. dimensions:', 3)


## `reshape`
The `reshape` function returns a new `ndarray` object pointing at the *same* data. This means that modifying one array will also modify the other.

In [40]:
g2 = g.reshape(4,6)
print(g2)
print("No. dimensions:", g2.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
('No. dimensions:', 2)


Set item at row 1, col 2 to 999 (more about indexing below).

In [41]:
g2[1, 2] = 999
g2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7, 999,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

The corresponding element in `g` has been modified.

In [42]:
g

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [999,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

## `ravel`
Finally, the `ravel` function returns a new one-dimensional `ndarray` that also points to the same data:

In [43]:
g.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# Arithmetic operations
All the usual arithmetic operators (`+`, `-`, `*`, `/`, `//`, `**`, etc.) can be used with `ndarray`s. They apply *elementwise*:

In [44]:
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])
print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a // b  =", a // b)
print("a % b  =", a % b)
print("a ** b =", a ** b)

('a + b  =', array([19, 27, 35, 43]))
('a - b  =', array([ 9, 19, 29, 39]))
('a * b  =', array([70, 92, 96, 82]))
('a / b  =', array([ 2,  5, 10, 20]))
('a // b  =', array([ 2,  5, 10, 20]))
('a % b  =', array([4, 3, 2, 1]))
('a ** b =', array([537824, 279841,  32768,   1681]))


Note that the multiplication is *not* a matrix multiplication. We will discuss matrix operations below.

The arrays must have the same shape. If they do not, NumPy will apply the *broadcasting rules*.

# Conditional operators

The conditional operators also apply elementwise:

In [45]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])

And using broadcasting:

In [46]:
m < 25  # equivalent to m < [25, 25, 25, 25]

array([ True,  True, False, False])

This is most useful in conjunction with boolean indexing (discussed below).

In [47]:
m[m < 25]

array([20, -5])

__Exercise__: Create a 1D array, `arr`, that contains integers between 0 and 9. Extract odd numbers from `arr`?

In [3]:
import numpy as np

arr = np.arange(10)
arr[arr % 2 == 1]


array([1, 3, 5, 7, 9])

__Exercise__: Given two 1D arrays, `a` and `b`, get the positions where elements of `a` and `b` match and return those elements.

((array([1, 3, 5, 7]),), array([ 2,  2,  4, -1]))


__Exercise__: Given a 1D array, `arr`, extract all numbers between 5 and 10 from this array.

array([ 7, 10,  7,  9,  8])

# Mathematical and statistical functions

Many mathematical and statistical functions are available for `ndarray`s.

## `ndarray` methods
Some functions are simply `ndarray` methods, for example:

In [51]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("mean =", a.mean())

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]
('mean =', 6.766666666666667)


Note that this computes the mean of all elements in the `ndarray`, regardless of its shape.

Here are a few more useful `ndarray` methods:

In [52]:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var):
    print(func.__name__, "=", func())

('min', '=', -2.5)
('max', '=', 12.0)
('sum', '=', 40.6)
('prod', '=', -71610.0)
('std', '=', 5.084835843520964)
('var', '=', 25.855555555555554)


These functions accept an optional argument `axis` which lets you ask for the operation to be performed on elements along the given axis. For example:

In [53]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
c.sum(axis=0)  # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [55]:
c.sum(axis=1)  # sum across rows

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

You can also sum over multiple axes:

In [56]:
c.sum(axis=(0,2))  # sum across matrices and columns

array([ 60,  92, 124])

In [57]:
0+1+2+3 + 12+13+14+15, 4+5+6+7 + 16+17+18+19, 8+9+10+11 + 20+21+22+23

(60, 92, 124)

## Universal functions
NumPy also provides fast **elementwise** functions called *universal functions*, or **ufunc**. They are vectorized wrappers of simple functions. For example `square` returns a new `ndarray` which is a copy of the original `ndarray` except that each element is squared:

In [58]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

array([[  6.25,   9.61,  49.  ],
       [100.  , 121.  , 144.  ]])

Here are a few more useful unary ufuncs:

In [59]:
print("Original ndarray")
print(a)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, 
             np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))

Original ndarray
[[-2.5  3.1  7. ]
 [10.  11.  12. ]]
('\n', 'absolute')
[[ 2.5  3.1  7. ]
 [10.  11.  12. ]]
('\n', 'sqrt')
[[       nan 1.76068169 2.64575131]
 [3.16227766 3.31662479 3.46410162]]
('\n', 'exp')
[[8.20849986e-02 2.21979513e+01 1.09663316e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]
('\n', 'log')
[[       nan 1.13140211 1.94591015]
 [2.30258509 2.39789527 2.48490665]]
('\n', 'sign')
[[-1.  1.  1.]
 [ 1.  1.  1.]]
('\n', 'ceil')
[[-2.  4.  7.]
 [10. 11. 12.]]
('\n', 'modf')
(array([[-0.5,  0.1,  0. ],
       [ 0. ,  0. ,  0. ]]), array([[-2.,  3.,  7.],
       [10., 11., 12.]]))
('\n', 'isnan')
[[False False False]
 [False False False]]
('\n', 'cos')
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in sqrt
  
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in log
  


## Binary ufuncs
There are also many binary ufuncs, that apply elementwise on two `ndarray`s.  Broadcasting rules are applied if the arrays do not have the same shape:

In [60]:
a = np.array([1, -2, 3, 4])
b = np.array([2, 8, -1, 7])
np.add(a, b)  # equivalent to a + b

array([ 3,  6,  2, 11])

In [61]:
np.greater(a, b)  # equivalent to a > b

array([False, False,  True, False])

In [62]:
np.maximum(a, b)

array([2, 8, 3, 7])

In [63]:
np.copysign(a, b) # changes the sign of a to that of b, element-wise.

array([ 1.,  2., -3.,  4.])

# Array indexing
## One-dimensional arrays
One-dimensional NumPy arrays can be accessed more or less like regular python arrays:

In [64]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[3]

19

In [65]:
a[2:5]

array([ 3, 19, 13])

In [66]:
a[2:-1]

array([ 3, 19, 13,  7])

In [67]:
a[:2]

array([1, 5])

In [68]:
a[2::2]

array([ 3, 13,  3])

In [69]:
a[::-1]

array([ 3,  7, 13, 19,  3,  5,  1])

Of course, you can modify elements:

In [70]:
a[3]=999
a

array([  1,   5,   3, 999,  13,   7,   3])

You can also modify an `ndarray` slice:

In [71]:
a[2:5] = [997, 998, 999]
a

array([  1,   5, 997, 998, 999,   7,   3])

## Differences with regular python arrays
Contrary to regular python arrays, if you assign a single value to an `ndarray` slice, it is copied across the whole slice, thanks to broadcasting rules discussed above.

In [72]:
a[2:5] = -1
a

array([ 1,  5, -1, -1, -1,  7,  3])

Also, you cannot grow or shrink `ndarray`s this way:

In [73]:
try:
    a[2:5] = [1,2,3,4,5,6]  # too long
except ValueError as e:
    print(e)

cannot copy sequence with size 6 to array axis with dimension 3


You cannot delete elements either:

In [74]:
try:
    del a[2:5]
except ValueError as e:
    print(e)

cannot delete array elements


Last but not least, `ndarray` **slices are actually *views*** on the same data buffer. This means that if you create a slice and modify it, you are actually going to modify the original `ndarray` as well!

In [75]:
a_slice = a[2:6]
a_slice[1] = 1000
a  # the original array was modified!

array([   1,    5,   -1, 1000,   -1,    7,    3])

In [76]:
a[3] = 2000
a_slice  # similarly, modifying the original array modifies the slice!

array([  -1, 2000,   -1,    7])

If you want a copy of the data, you need to use the `copy` method:

In [77]:
another_slice = a[2:6].copy()
another_slice[1] = 3000
a  # the original array is untouched

array([   1,    5,   -1, 2000,   -1,    7,    3])

In [78]:
a[3] = 4000
another_slice  # similary, modifying the original array does not affect the slice copy

array([  -1, 3000,   -1,    7])

## Multi-dimensional arrays
Multi-dimensional arrays can be accessed in a similar way by providing an index or slice for each axis, separated by commas:

In [79]:
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [80]:
b[1, 2]  # row 1, col 2

14

In [81]:
b[1, :]  # row 1, all columns

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [82]:
b[:, 1]  # all rows, column 1

array([ 1, 13, 25, 37])

**Caution**: note the subtle difference between these two expressions: 

In [83]:
b[1, :]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [84]:
b[1:2, :]

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

The first expression returns row 1 as a 1D array of shape `(12,)`, while the second returns that same row as a 2D array of shape `(1, 12)`.

## Fancy indexing
You may also specify a list of indices that you are interested in. This is referred to as *fancy indexing*.

In [85]:
b[(0,2), 2:5]  # rows 0 and 2, columns 2 to 4 (5-1)

array([[ 2,  3,  4],
       [26, 27, 28]])

In [86]:
b[:, (-1, 2, -1)]  # all rows, columns -1 (last), 2 and -1 (again, and in this order)

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

If you provide multiple index arrays, you get a 1D `ndarray` containing the values of the elements at the specified coordinates.

In [87]:
b[(-1, 2, -1, 2), (5, 9, 1, 9)]  # returns a 1D array with b[-1, 5], b[2, 9], b[-1, 1] and b[2, 9] (again)

array([41, 33, 37, 33])

## Higher dimensions
Everything works just as well with higher dimensional arrays, but it's useful to look at a few examples:

In [88]:
c = b.reshape(4,2,6)
c

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [89]:
c[2, 1, 4]  # matrix 2, row 1, col 4

34

In [90]:
c[2, :, 3]  # matrix 2, all rows, col 3

array([27, 33])

If you omit coordinates for some axes, then all elements in these axes are returned:

In [91]:
c[2, 1]  # Return matrix 2, row 1, all columns.  This is equivalent to c[2, 1, :]

array([30, 31, 32, 33, 34, 35])

## Boolean indexing
You can also provide an `ndarray` of boolean values on one axis to specify the indices that you want to access.

In [92]:
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [93]:
rows_on = np.array([True, False, True, False])
b[rows_on, :]  # Rows 0 and 2, all columns. Equivalent to b[(0, 2), :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [94]:
cols_on = np.array([False, True, False] * 4)
b[:, cols_on]  # All rows, columns 1, 4, 7 and 10

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

If you use a boolean array that has the same shape as the `ndarray`, then you get in return a 1D array containing all the values that have `True` at their coordinate. This is generally used along with conditional operators:

In [95]:
b[b % 3 == 1]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46])

# Iterating
Iterating over `ndarray`s is very similar to iterating over regular python arrays. **Note that iterating over multidimensional arrays is done with respect to the first axis.**

In [96]:
c = np.arange(24).reshape(2, 3, 4)  # A 3D array (composed of two 3x4 matrices)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [97]:
for m in c:
    print("Item:")
    print(m)

Item:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Item:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [98]:
for i in range(len(c)):  # Note that len(c) == c.shape[0]
    print("Item:")
    print(c[i])

Item:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Item:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


If you want to iterate on *all* elements in the `ndarray`, simply iterate over the `flat` attribute:

In [99]:
for i in c.flat:
    print("Item:", i)

('Item:', 0)
('Item:', 1)
('Item:', 2)
('Item:', 3)
('Item:', 4)
('Item:', 5)
('Item:', 6)
('Item:', 7)
('Item:', 8)
('Item:', 9)
('Item:', 10)
('Item:', 11)
('Item:', 12)
('Item:', 13)
('Item:', 14)
('Item:', 15)
('Item:', 16)
('Item:', 17)
('Item:', 18)
('Item:', 19)
('Item:', 20)
('Item:', 21)
('Item:', 22)
('Item:', 23)


# Stacking arrays
It is often useful to stack together different arrays. NumPy offers several functions to do just that. Let's start by creating a few arrays.

In [100]:
q1 = np.full((3,4), 1.0)
q1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [101]:
q2 = np.full((4,4), 2.0)
q2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [102]:
q3 = np.full((3,4), 3.0)
q3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

## `vstack`
Now let's stack them vertically using `vstack`:

In [103]:
q4 = np.vstack((q1, q2, q3))
q4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [104]:
q4.shape

(10, 4)

This was possible because q1, q2 and q3 all have the same shape (except for the vertical axis, but that's ok since we are stacking on that axis).

## `hstack`
We can also stack arrays horizontally using `hstack`:

In [105]:
q5 = np.hstack((q1, q3))
q5

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

In [106]:
q5.shape

(3, 8)

This is possible because q1 and q3 both have 3 rows. But since q2 has 4 rows, it cannot be stacked horizontally with q1 and q3:

In [107]:
try:
    q5 = np.hstack((q1, q2, q3))
except ValueError as e:
    print(e)

all the input array dimensions except for the concatenation axis must match exactly


## `stack`
The `stack` function stacks arrays along a new axis. All arrays have to have the same shape.

In [108]:
q8 = np.stack((q1, q3))
q8

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [109]:
q8.shape

(2, 3, 4)

# Saving and loading
NumPy makes it easy to save and load `ndarray`s in binary or text format.

## Binary `.npy` format
Let's create a random array and save it.

In [110]:
a = np.random.rand(2,3)
a

array([[0.34648113, 0.72173914, 0.56280495],
       [0.5789223 , 0.53456353, 0.98098982]])

In [0]:
np.save("my_array", a)

Done! Since the file name contains no file extension was provided, NumPy automatically added `.npy`.

To load this file into a NumPy array, simply call `load`:

In [112]:
a_loaded = np.load("my_array.npy")
a_loaded

array([[0.34648113, 0.72173914, 0.56280495],
       [0.5789223 , 0.53456353, 0.98098982]])

## Text format
Let's try saving the array in text format:

In [0]:
np.savetxt("my_array.csv", a)

Now let's look at the file content:

In [114]:
with open("my_array.csv", "rt") as f:
    print(f.read())

3.464811298830767772e-01 7.217391358525677703e-01 5.628049532099513863e-01
5.789222990048279449e-01 5.345635251201927840e-01 9.809898189694526982e-01



This is a CSV file with tabs as delimiters. You can set a different delimiter:

In [0]:
np.savetxt("my_array.csv", a, delimiter=",")

To load this file, just use `loadtxt`:

In [116]:
a_loaded = np.loadtxt("my_array.csv", delimiter=",")
a_loaded

array([[0.34648113, 0.72173914, 0.56280495],
       [0.5789223 , 0.53456353, 0.98098982]])

# What next?
Now you know all the fundamentals of NumPy, but there are many more options available. The best way to learn more is to experiment with NumPy, and go through the excellent [reference documentation](http://docs.scipy.org/doc/numpy/reference/index.html) to find more functions and features you may be interested in.